vm_list = [
	{
		:name => "k8s-master",
		:eth1 => "192.168.100.21",
		:mem => "2048",
		:cpu => "2",
		:sshport => 22230
	},
	{
		:name => "k8s-work1",
		:eth1 => "192.168.100.22",
		:mem => "2048",
		:cpu => "2",
		:sshport => 22231
	},
	{
		:name => "k8s-work2",
		:eth1 => "192.168.100.23",
		:mem => "2048",
		:cpu => "2",
		:sshport => 22232
	}
]

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu-docker"
	Encoding.default_external = 'UTF-8'
	vm_list.each do |item|
		config.vm.define item[:name] do |config|
			config.vm.hostname = item[:name]
			config.vm.network "private_network", ip: item[:eth1]
			config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", disabled: "true"
			config.vm.network "forwarded_port", guest: 22, host: item[:sshport]
			#config.ssh.username = "root"
			#config.ssh.password = "root"
			#config.ssh.port=item[:sshport]
			#config.ssh.insert_key = false
			#config.vm.synced_folder ".", "/vagrant", type: "rsync" 
			config.vm.provider "vmware_fusion" do |v|
				v.vmx["memsize"] = item[:mem]
				v.vmx["numvcpus"] = item[:cpu]
			end
			config.vm.provider "virtualbox" do |v|
				v.memory = item[:mem];
				v.cpus = item[:cpu];
				v.name = item[:name];
			end
		end
	end
end

